name: AntiMobGrief
main: be.wolfstorm.antimobgrief.AntiMobGrief
version: 1.0-SNAPSHOT
author: Wolfstorm
commands:
  amg:
    description: Show Help for AntiMobGrief
    usage: /amg <command> <value>
permissions:
  antimobgrief.op:
    description: Give you access to all AntiMobGrief commands
    default: op