name: AntiMobGrief
main: be.wolfstorm.antimobgrief.AntiMobGrief
version: 1.0-SNAPSHOT
author: Wolfstorm
permissions:
  antimobgrief.op:
    description: Give you access to all AntiMobGrief commands
    default: op